gem 'gon'
gem 'formtastic'
gem 'cocoon'
gem 'little_sugar'
gem 'log4r'
gem 'haml-rails'
gem 'capybara-select2', group: :test
gem 'naturally-unicode'
# gem 'redmine_plugin_asset_pipeline'
gem 'therubyracer'
gem 'activerecord-import', '>= 0.2.0'

group :development do
  gem 'pry'
  gem 'better_errors'
  # Add advanced features for better_errors
  gem 'binding_of_caller'
end

group :assets do
  gem 'yui-compressor'
  gem 'uglifier'
  gem 'coffee-rails'
  gem 'sass-rails'
  gem 'compass-rails'
  gem 'zen-grids'
end